apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app
        image: jmenzies722/ci-cd-project:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
spec:
  type: LoadBalancer
  selector:
    app: ci-cd-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
