name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker CLI and Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-project:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-project:latest

      # Step 4: Set up kubectl and kubeconfig
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0' # Use a stable kubectl version

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      # Step 5: Verify Kubernetes Cluster Access
      - name: Verify Kubernetes Cluster Access
        run: |
          kubectl cluster-info
          kubectl get nodes

      # Step 6: Deploy Application to Kubernetes
      - name: Deploy Application
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/ci-cd-app

      # Step 7: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get all
          kubectl describe deployment ci-cd-app
          kubectl get services
