name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build and Test the Code
  build-test:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  # Job 2: Build and Push Docker Image
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-test
    environment: CI-CD

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Docker Secrets
        run: |
          echo "Docker Username Set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "Docker Password Set: ${{ secrets.DOCKER_PASSWORD != '' }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t jmenzies722/ci-cd-project:latest .

      - name: Push Docker Image
        run: |
          docker push jmenzies722/ci-cd-project:latest

  # Job 3: Deploy to Kubernetes
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-push
    environment: CI-CD

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up kubectl and kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Verify Kubernetes Cluster Access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/ci-cd-app
